# Generated by Django 5.2.1 on 2025-06-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_experience_description_experience_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='summary',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
