# Generated by Django 5.2.1 on 2025-06-03 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_description', models.TextField()),
                ('job_details', models.JSONField(blank=True, default=dict, null=True)),
                ('proposal', models.TextField()),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('viewed', 'Viewed'), ('rejected', 'Rejected')], default='generated', max_length=20)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
