# Generated by Django 5.2.1 on 2025-06-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='proposal',
            new_name='proposal_text',
        ),
        migrations.AddField(
            model_name='proposal',
            name='style',
            field=models.CharField(choices=[('default', 'Default'), ('professional', 'Professional'), ('creative', 'Creative'), ('solutions', 'Solutions-Focused'), ('casual', 'Casual'), ('technical', 'Technical')], default='default', max_length=20),
        ),
    ]
